### ISSUE TITLE
Bad source reference for H5P JS files with multi installation setups

### ISSUE THREAD

**Issue by fsesterh** [studer-raimann/H5P#1] opened 2018-05-11 08:55 UTC
I run multiple ILIAS Installations on one development system. One from our own code repo, and one from the ILIAS Core etc.

The URLs look like this:

https://devel-ilias.th-koeln.de/thkoeln
https://devel-ilias.th-koeln.de/core

After installing the H5P plugin and refreshing the H5P hub, and installing ALL of the content types I wasn't able to create a new object or rather a new content type within the object because the necessary javascript files for selecting a library won't load. ILIAS tries to GET:

10:32:04.371 Laden fehlgeschlagen für das <script> mit der Quelle "https://devel-ilias.th-koeln.de/Customizing/global/plugins/Services/Repository/RepositoryObject/H5P/vendor/h5p/h5p-core/js/h5p-content-type.js". ilias.php:777

etc.
Which will never work, since the subfolder ../thkoeln/.. is missing.

Code looks like this:

<script src="/./Customizing/global/plugins/Services/Repository/RepositoryObject/H5P/vendor/h5p/h5p-core/js/h5p-content-type.js"></script>

ilias.ini.php has the correct docroot for ILIAS:

http_path = "https://devel-ilias.th-koeln.de/thkoeln"

**Comment by theodortruffer** [comment] 2018-05-16 12:10
Hello @fsesterh,
Apparently we haven't tested the plugin on ILIAS installations with relative URLs. We will try to fix that issue as soon as possible and inform you when it's done.

**Comment by theodortruffer** [comment] 2018-05-24 06:56
Hey @fsesterh,
we changed the source path in the latest version and added a constant which should now correctly build the relative URL. 
Can you confirm that this issue is fixed or does it still occur on your installation?

**Comment by fsesterh** [comment] 2018-05-24 07:04
Works fine for me now, thanks!

**Comment by damlay86** [comment] 2018-11-30 14:02
Hello, 

we are running also multiple ILIAS Installations on one development System. Therefore, we are stuck into the same Problem (the libraryelements won't loading). 

We appreciate any help!

**Comment by damlay86** [comment] 2018-12-04 13:22
@fwyss-srag
 
it is still the same. I attached a screenshot of it. 
![image](https://user-images.githubusercontent.com/45490046/49444594-e6f66b00-f7cf-11e8-9025-24b265bb586e.png)
Thanks for answering!

**Comment by fwyss-srag** [comment] 2018-12-04 13:36
@damlay86 
I did not test Interactive Video, you're right.

Tests have shown that this is not because of the subfolders, but when multiple versions of Interactive Video are installed.

Can you please uninstall all Interactive Video versions and then reinstall it?

**Comment by fsesterh** [comment] 2018-12-04 13:52
I just did a git pull:

# git pull
remote: Enumerating objects: 50, done.
remote: Counting objects: 100% (50/50), done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 50 (delta 24), reused 50 (delta 24), pack-reused 0
Unpacking objects: 100% (50/50), done.
From https://github.com/studer-raimann/H5P
   829f596..0e7edd6  master     -> origin/master
 * [new tag]         v2.0.1     -> v2.0.1
Updating 829f596..0e7edd6
Fast-forward
 CHANGELOG.md                              |   4 ++++
 composer.lock                             |  14 +++++++-------
 lang/ilias_de.lang                        |   4 ++--
 lang/ilias_en.lang                        |   2 +-
 plugin.php                                |   5 ++++-
 src/Utils/H5P.php                         |   2 +-
 vendor/composer/autoload_classmap.php     |   1 +
 vendor/composer/autoload_psr4.php         |   4 ++--
 vendor/composer/autoload_static.php       |   9 +++++----
 vendor/composer/installed.json            |  12 ++++++------
 vendor/srag/dic/CHANGELOG.md              |   9 +++++++++
 vendor/srag/dic/src/PHPVersionChecker.php | 153 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 12 files changed, 195 insertions(+), 24 deletions(-)
 create mode 100644 vendor/srag/dic/src/PHPVersionChecker.php

After that I tried to create a new content (type = Drag and Drop) and got this syntax error:

14:46:48.072 SyntaxError: expected expression, got end of script[Weitere Informationen] h5peditor.js:1:3560
	ns.libraryRequested https://devel-ilias.th-koeln.de/thkoeln/Customizing/global/plugins/Services/Repository/RepositoryObject/H5P/vendor/h5p/h5p-editor/scripts/h5peditor.js:78:17
	success https://devel-ilias.th-koeln.de/thkoeln/Customizing/global/plugins/Services/Repository/RepositoryObject/H5P/vendor/h5p/h5p-editor/scripts/h5peditor.js:137:11
	c https://devel-ilias.th-koeln.de/thkoeln/Customizing/global/plugins/Services/Repository/RepositoryObject/H5P/vendor/h5p/h5p-core/js/jquery.js:2:7852
	fireWith https://devel-ilias.th-koeln.de/thkoeln/Customizing/global/plugins/Services/Repository/RepositoryObject/H5P/vendor/h5p/h5p-core/js/jquery.js:2:8658
	k https://devel-ilias.th-koeln.de/thkoeln/Customizing/global/plugins/Services/Repository/RepositoryObject/H5P/vendor/h5p/h5p-core/js/jquery.js:4:14013
	r https://devel-ilias.th-koeln.de/thkoeln/Customizing/global/plugins/Services/Repository/RepositoryObject/H5P/vendor/h5p/h5p-core/js/jquery.js:4:18226

**Comment by fsesterh** [comment] 2018-12-04 14:00
Note: This only happens on DEV with relative URLs agian, not on my QA installation. Weird.

**Comment by damlay86** [comment] 2018-12-04 14:14
@fwyss-srag I uninstall and reinstall interaktive Video in the Library. I regret to say that it does not solve the Problem. I noticed that this Problem happens when I want to use all new library Elements that came with the Plug-In V2.0.

**Comment by fwyss-srag** [comment] 2018-12-04 14:14
@fsesterh Uninstall and reinstall of Drag'n'Drop not help?

**Comment by fwyss-srag** [comment] 2018-12-04 14:15
@damlay86 Which error come in JavaScript console?

**Comment by damlay86** [comment] 2018-12-04 14:34
@fwyss-srag 
here is it:

![image](https://user-images.githubusercontent.com/45490046/49448855-06929100-f7da-11e8-8530-81d26b27a36b.png)

**Comment by damlay86** [comment] 2018-12-04 14:43
the right one is this: 
![image](https://user-images.githubusercontent.com/45490046/49449509-5887e680-f7db-11e8-903b-368e7c04b536.png)

**Comment by fsesterh** [comment] 2018-12-04 15:06
> 
> 
> @fsesterh Uninstall and reinstall of Drag'n'Drop not help?

Can I safely uninstall old versions of a content-type library if there is content using them? This will be the case when we updade on our production environment. As I understood this, the old libraries are kept so that content using them still works?

**Comment by theodortruffer** [comment] 2018-12-06 09:00
@fsesterh No, we would not recommend to do that. The existing contents would probably not work anymore. 
We are still trying to reproduce and fix the bug and will inform you when we succeed (or need more information).

**Comment by fsesterh** [comment] 2018-12-11 13:19
It's weird. I git pulled the latest version and it seems to have fixed itself, without the need to delete any libraries. I can only attach the latest git pull from shell. Update was for 2.1.0 to start testing the latest enhancements for the iframe embedder.
[h5p-gitpull-181210.txt](https://github.com/studer-raimann/H5P/files/2667694/h5p-gitpull-181210.txt)

**Comment by theodortruffer** [comment] 2018-12-11 14:37
@fsesterh That's weird, yes - but I'm glad it works. ;)
@damlay86 do you still experience this bug?

**Comment by damlay86** [comment] 2018-12-13 10:00
@theodortruffer it is working! 👍  thanks a lot for your help and patience :)

**Comment by theodortruffer** [comment] 2018-12-13 10:23
Great! Thanks go to fwyss, he did the actual work. ;) 
I'll close the Issue then.

**Closed by theodortruffer** 2018-12-13 10:23 UTC
Labels: bug
