### ISSUE TITLE
Interactive videos with YouTube URL broken since H5P 1.18

### ISSUE THREAD

**Issue by fsesterh** [studer-raimann/H5P#3] opened 2018-06-06 08:26 UTC
I've reported a bug we discovered in the core H5P project that concerns the use of interactive videos that are using youtube links. This type of content was working fine until you updated the core H5P files to version 1.18 - or at least that is my suspicion.
The error appears when trying to edit or access an interactive video with a youtube link.

I've reported the bug here:
https://h5ptechnology.atlassian.net/browse/HFP-2038

The H5P devs don't know the ILIAS plugin and are asking if you are using the stable branch or the master branch of H5P with the ILIAS-Plugin?

The error I get is thrown in:
#18 Whoops\Exception\ErrorException in /var/www/html/thkoeln/Customizing/global/plugins/Services/Repository/RepositoryObject/H5P/vendor/h5p/h5p-core/h5p.classes.php:3646

You can find the full stracktrace in the jira issue I've linked above.

**Comment by fsesterh** [comment] 2018-06-13 13:04
Has this been seen :)? There is no way to report (possible) bugs in the ILIAS mantis, because there is no H5P plugin category in the ILIAS plugin project (which would be nice by the way!).

**Comment by theodortruffer** [comment] 2018-06-13 13:18
Yes, sorry for the late answer! We will probably be opening a service desk with a certain email address soon, but for now, you will need to report bugs here or at our support address support@studer-raimann.ch.
Also, we can't prioritize bugs for every plugin we publish on github - if you're interested in a prioritized bug fixing and a upgrade guarantee, please contact us for an SLA (Service Level Agreement).

Concerning the bug: As far as I know, we are using H5P versions 1.17.0 (see here: https://github.com/studer-raimann/H5P/blob/master/composer.json), which was installed via composer. But I'm not sure which branch this is, I'll have to ask our developer who implemented the plugin (who is not working today, unfortunately).

**Comment by fsesterh** [comment] 2018-06-13 13:28
No need to be sorry! The plugin is a very good one in my book so far, and if needed we would consider prioritising bugs. Since the plugin is made available as an open source licence I would posts bugs here or in mantis to allow others to read bug report as well.

It looks like you are using version 1.18 of the plugin atm. At least the git says
"Update h5p core module to 1.18" for the folder /vendor/h5p - last changed 20 days ago. You were using 1.17 before that and I can confirm that youtube vids were working before.

**Comment by theodortruffer** [comment] 2018-06-15 06:01
So our developer confirmed that we are using the stable branch of the H5P repository. But unfortunately we couldn't reproduce this error.
Could you maybe send the database entry of this exact H5P content? It should be found in the table 'rep_robj_xhfp_cont'.

**Comment by fsesterh** [comment] 2018-06-19 09:23
Here is the SQL export of the interactive video. When editing the described error appears.
[rep_robj_xhfp_cont.zip](https://github.com/studer-raimann/H5P/files/2114593/rep_robj_xhfp_cont.zip)

There also seems to be a problem with creating a new interactive video with a youtube link in the current build. I can't save such videos anymore. There is an error given in the form: -rep_robj_xhfp_xhfp_incomplete_content-

![19-06-_2018_11-21-57](https://user-images.githubusercontent.com/29703577/41588837-1ff4a030-73b3-11e8-9c3f-93551800e433.jpg)

**Comment by fsesterh** [comment] 2018-06-22 09:54
You are correct: As of "now" H5P interactive videos require a summary. This requires field is hidden in the thirs step during creation. That is a bit unfortunate, but ok. I can only assume that before the summary was **not** required and the video could be saved(?). Because all interactive videos I created before still break when I try to edit them -> they do not have a summary. Creating a video now - including a summary - works. Editing such a video **with a summary** also works...

Anyways, I can't reproduce this anymore so this report can be closed.

**Comment by theodortruffer** [comment] 2018-06-22 10:18
It's possible that this field was not required in older versions. 
Okay, I'll close this report.

**Closed by theodortruffer** 2018-06-22 10:18 UTC

**Comment by damlay86** [comment] 2018-12-13 12:49
I`ve the same Problem with the Videos. I reload languages and did not get any error Messages. I filled out every required field but still can not link any Video URL neither in interactive Video nor in Course presentation.  
![image](https://user-images.githubusercontent.com/45490046/49939701-d33cba00-fedd-11e8-8d44-312bb57f4a87.png)
